### PR TITLE
Truncate numbers with excess decimals

### LINKED ISSUE #409: Decimals aren't handled correctly for item based currencies resulting in infinite money
#### What is the issue/bug you're experiencing?

The way TNE handles decimals is incorrect, at least for item based currencies. I initially found out thanks to the help at:

https://github.com/Ghost-chu/QuickShop-Reremake/issues/414

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)

`/money give <player> 0.3333`

The amount they actually receive will be `33.33`. This is annoying when plugins try to give fractional amounts to TNE, since it causes players to get double chest after double chest of money depending on the amount of decimal digits. 

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9

#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119b

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.

None

#### Spigot/Bukkit version?

git-Paper-176

#### Is your server run in online mode?

Yes.

#### The exact command you ran w/ arguments?
`/money give Binero 0.3333`

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/NdQVsf4yj4/

#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/trwqdFrjYm/ (redacted private information)

### PR DESCRIPTION
**Pull request by Binero**
Fixes #409 by truncating numbers that exceed the amount of decimals for a number.

### CODE REVIEW

File: TNE/src/net/tnemc/core/common/currency/ItemCalculations.java [hunk 1]
```diff
@@ -132,13 +133,21 @@ public static void setItems(UUID account, TNECurrency currency, BigDecimal amoun
       boolean add = (consolidate) || amount.compareTo(old) >= 0;
       if(remove) add = false;
 
-      if(consolidate) split = (amount.toPlainString() + (amount.toPlainString().contains(".")? "" : ".00")).split("\\.");
+      if(consolidate) split = (amount.toPlainString() + (amount.toPlainString().contains(".")? "" : "0.00")).split("\\.");
```
Comment (Binero) [inline TNE/src/net/tnemc/core/common/currency/ItemCalculations.java:136]: This needs to be `.00`.

Comment (creatorfromhell) [reply TNE/src/net/tnemc/core/common/currency/ItemCalculations.java:136]: Are you saying that it needs to be .00 instead of the 0.00 you added?

Comment (Binero) [reply TNE/src/net/tnemc/core/common/currency/ItemCalculations.java:136]: Yup. I'll get around to it. Been busy lately.
